spring:
  datasource:
   url:
   username: postgres
   password:
   hikari:
     maximum-pool-size: 10
     minimum-idle: 5
     jdbc-url:
  mail:
      host: smtp.gmail.com
      port: 587
      username: vasyl.pahomenko2018@gmail.com
      password: gvcofrelbcfffynp
      protocol: smtp
      tls: true
      properties.mail.smtp:
        auth: true
        starttls.enable: true
        ssl.trust: smtp.gmail.com
      test-connection: true
  google:
      googleClientId: 134665215077-alj0sn4e16980oc56ft1lq0v0aa3j6uj.apps.googleusercontent.com
      googleClientSecret: 2mUXvgYCEyN9hvnZoI07eRrd
      googleRedirectUri: http://localhost:8080/googleAccount/oauth2callback

application:
  protocol: https
  host: report.inventorsoft.co

jwt:
  expiration: 360000
  secret: adada54g,a,dbabd_1
  tokenprefix: Bearer
  headerstring: Authorization
