spring:
  datasource:
   url: jdbc:postgresql://localhost:5432/reporttool
   username: postgres
   password: postgres
   hikari:
     maximum-pool-size: 10
     minimum-idle: 10
     jdbc-url: jdbc:postgresql://localhost:5432/reporttool

application:
  protocol: http
  host: localhost:8080

jwt:
  expiration: 360000
  secret: teststring
  tokenprefix: Bearer
  headerstring: Authorization
