locale:
  languageTag: en_US
spring:
  profiles:
    active: dev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        temp.use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  main:
    banner-mode: 'off'
  liquibase:
    change-log: classpath:/db/master.xml