spring:
  datasource:
   url: jdbc:postgresql://localhost:5432/reporttool
   username: postgres
   password: postgres
   hikari:
     maximum-pool-size: 10
     minimum-idle: 10
  mail:
      host: smtp.gmail.com
      port: 587
      username: vasyl.pahomenko2018@gmail.com
      password: gvcofrelbcfffynp
      protocol: smtp
      tls: true
      properties.mail.smtp:
        auth: true
        starttls.enable: true
        ssl.trust: smtp.gmail.com
      test-connection: true
  google:
      googleClientId: 835351722802-6hnnj1nind8nmrua4qa7pd13bnsp4qgu.apps.googleusercontent.com
      googleClientSecret: sd8nWf2D5QGfDX6uWiHCp8Se
      googleRedirectUri: http://localhost:8080/app/no-auth/googleAccount/oauth2callback

application:
  protocol: http
  host: localhost:8080

jwt:
  expiration: 14400000
  secret: teststring
  token-prefix: Bearer
  header-string: Authorization

cors:
  origins: '*'

encryption:
  public-key: M02cnQ51Ji97vwT4

