spring:
  datasource:
   url: jdbc:postgresql://localhost:5432/reporttool
   username: postgres
   password: postgres
   hikari:
     maximum-pool-size: 10
     minimum-idle: 10
  db-foo:
    datasource:
      url: jdbc:h2:mem:foo;DB_CLOSE_ON_EXIT=FALSE
      username: username_1
      password: password_1
      driver-class-name: org.h2.Driver
      test-on-borrow: true
      validation-query: SELECT 1 FROM dual
  db-bar:
    datasource:
      url: jdbc:h2:mem:bar;DB_CLOSE_ON_EXIT=FALSE
      username: username
      password: password
      driver-class-name: org.h2.Driver
      test-on-borrow: true
      validation-query: SELECT 1 FROM dual
  mail:
      host: smtp.gmail.com
      port: 587
      username: vasyl.pahomenko2018@gmail.com
      password: gvcofrelbcfffynp
      protocol: smtp
      tls: true
      properties.mail.smtp:
        auth: true
        starttls.enable: true
        ssl.trust: smtp.gmail.com
      test-connection: true
  google:
      googleClientId: 134665215077-alj0sn4e16980oc56ft1lq0v0aa3j6uj.apps.googleusercontent.com
      googleClientSecret: 2mUXvgYCEyN9hvnZoI07eRrd
      googleRedirectUri: http://localhost:8080/googleAccount/oauth2callback

application:
  protocol: http
  host: localhost:8080

jwt:
  expiration: 5000
  secret: teststring
  token-prefix: Bearer
  header-string: Authorization

cors:
  origins: '*'

encryption:
  public-key: M02cnQ51Ji97vwT4