ALTER TABLE charts ADD COLUMN group_id BIGINT NOT NULL DEFAULT 0;
ALTER TABLE charts ADD CONSTRAINT GROUP_FK
FOREIGN KEY (group_id)
REFERENCES groups (id)
ON DELETE CASCADE;
ALTER TABLE charts ALTER COLUMN group_id DROP DEFAULT;